$(".donate-page__button").on("click",function(){$(".donate-page__first-step").fadeOut(300,function(){$(".donate-page__payment-step").fadeIn(300);});});$("form").on("submit",preventDefault);$(document).on("input","input.-number",function(){const min=$(this).data("min");const max=$(this).data("max");let val=formatAmountValue(this.value);val=val[0]==="0"?min:val;val=val>max?max:val;this.value=val;if(this.value.length){$(this).closest(".input").addClass("-filled");}else{$(this).closest(".input").removeClass("-filled");}
if(this.value>=min&&this.value<=max){$(this).closest("form").removeClass("-disabled");}else{$(this).closest("form").addClass("-disabled");}});$(document).on("blur","input.-number",function(){const min=$(this).data("min");const max=$(this).data("max");if(this.value){this.value=this.value<min?min:this.value;}
if(this.value>=min&&this.value<=max){$(this).closest("form").removeClass("-disabled");}else{$(this).closest("form").addClass("-disabled");}});function formatAmountValue(value){let formattedValue=value.replace(/[^0-9\.]/g,"");if(formattedValue.split(".").length-1>1){formattedValue=formattedValue.replace(".","");}
if(formattedValue[0]==="."){formattedValue=formattedValue.slice(1);}
if(formattedValue.slice(-2)===".."){formattedValue=formattedValue.slice(0,-1);}
if(formattedValue.match(/\.(\d+)/)&&formattedValue.match(/\.(\d+)/)[1].length>2){formattedValue=parseInt(formattedValue*100)/100;}
return formattedValue;}
const publicTokens={uah:"eec1beyiKasha2quaib7weiR8tahXeeg",uahWorld:"chaeNgohghateuleengaephieCh2dejo",usdWorld:"leid3raiKaiX0oochaDe2eexaf8ainei",uahBinancePay:"the2Quei0Ahfa0ii7oozeibie5joo7Eo"};$(".payment-button").on("click",function(){const locale=$("html").attr("lang").toLowerCase();const paramLocale=locale==="uk"?"ua":locale;const paymentType=$(this).data("payment-type");const publicToken=publicTokens[paymentType];const amount=$(this).closest("form").find("input").val();const amountPennies=getPenniesFromAmount(amount);const currency=$(this).closest("form").data("currency").toUpperCase();redirectToPay(publicToken,amountPennies,paramLocale,currency);});function getPenniesFromAmount(amount){const trunc=Math.trunc(amount);return Math.ceil(trunc*100+(amount-trunc)*100);}
function redirectToPay(publicToken,amount,locale,currency){let data={public_token:publicToken,amount:amount,locale:locale,currency:currency,description:"donate for Ukraine"};return fetch("https://api.4bill.io/widget/acquiring/create",{method:"POST",headers:{"Content-Type":"application/json;charset=utf-8"},body:JSON.stringify(data)}).then(response=>{return response.json();}).then(data=>{let payUrl=data["pay_url"];if(!payUrl){alert(JSON.stringify({errorInfo:data}));return;}
window.location.href=payUrl;});}
function openPaymentWindow(){lockScroll();$(".payment-info-window").addClass("-open");}
function closePaymentWindow(){if($(".payment-info-window").hasClass("-open")){unlockScroll();$(".payment-info-window").removeClass("-open");}}
$(".open-payment-info").on("click",openPaymentWindow);$(".payment-info-window__block-close").on("click",closePaymentWindow);customClickOutsideCallback(".payment-info-window__block",closePaymentWindow);$(window).on("load",function(){OverlayScrollbars($(".payment-info-window__list")[0],{});});$(window).on("load",function(){$("body").addClass("-loaded");});